# Generated by Django 3.0.7 on 2020-06-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriprion', models.CharField(max_length=220)),
                ('url', models.URLField(blank='true')),
                ('image', models.ImageField(height_field=200, upload_to='project_image', width_field=300)),
            ],
        ),
    ]
